server:
  port: 8087
#  error:
#    path: /aaa
#  servlet:
#    context-path: /bb
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/auth8?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  freemarker:
    cache: false
    content-type: text/html
    suffix: .ftlh
    template-loader-path: classpath:/templates/
logging:
  level:
    root: info
    io.cubita.base.auth.dao: trace
    io.cubita.base.auth.mydao: trace
  pattern:
    console: '%p %m %n'
#management:
#  endpoint:
#    health:
#      show-details: always
#  endpoints:
#    web:
#      exposure:
#        include:
#          - 'filters'
zuulex:
#  use-filter: true
#  routes:
#    default:
#      path: /**
#      url: 'forward:'
  tenant:
    admin: admin
#cubita:
#  web:
#    service:
#      error:
#        enabled: false