server:
  port: 8087
#  servlet:
#    context-path: /bb
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/auth8?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
logging:
  level:
    root: info
    io.cubita.base.auth.dao: trace
    io.cubita.base.auth.mydao: trace
  pattern:
    console: '%p %m %n'
#zuulex:
#  servlet-path: /*
#zuulex:
#  use-filter: false
#  servlet-path: /ccc




